name: Release domain

on:
  # manually
  workflow_dispatch:
    inputs:
      payara_version:
        description: 'Payara version (e.g. 6.2024.12)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout builder
      uses: actions/checkout@v5

    - name: Checkout payara
      uses: actions/checkout@v5
      with:
        repository: payara/Payara
        path: Payara
        ref: payara-server-${{ inputs.payara_version }}

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build
      run: |
        mvn -B -q -DskipTests -f Payara/pom.xml package

    - name: Release
      uses: jreleaser/release-action@v2
      with:
        arguments: release
      env:
        JRELEASER_PROJECT_VERSION: ${{ inputs.payara_version }}
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}